sudo: false
language: node_js
node_js:
  - 'stable'
  - '7'
  - '6'
before_install: yarn install
script: yarn run travis
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
